### ISSUE TITLE
shortcut to setup permissions and groups in tests easier

### ISSUE THREAD

**Issue by LilithWittmann** [serioeseGmbH/serious-django-permissions#5]
As a developer I want to use the groups and permissions inside my tests. Currently I have to do this manually via something like:

```python
from serious_django_permissions.management.commands import create_groups, create_permissions

class SomethingTest(TestCase):

    def setUp(self):
        create_permissions.Command.execute()
        create_groups.Command.execute()
```

It would be cooler if I could write something like:
```python
from serious_django_permissions.helpers import setup_permissions

class SomethingTest(TestCase):

    def setUp(self):
        setup_permissions()
```

**Comment by cobalamin** [comment]
That should work quite easily by just factoring out the creation logic inside the management commands to methods inside `helpers`, and then calling those from the management commands.

**Comment by seblat** [comment]
Is there any disadvantage doing this the other way round: Adding a simple `helper` function which references the existing `.handle()` functions, as I did above?

**Comment by cobalamin** [comment]
Just an organizational one, because that'd be the inverse of what most people expect in code structure. It'd essentially be defining a low-level function in terms of a high-level function instead of the other way around.

**Comment by seblat** [comment]
> That should work quite easily by just factoring out the creation logic inside the management commands to methods inside `helpers`, and then calling those from the management commands.

I've tried this in the above commit. I'm not sure if I've taken the advice too literally. @cobalamin could you take a look at this?

Regarding master, do I get this right: 
[`create_groups.Command.handle()` calls `create_permissions.Command.handle`.](https://github.com/serioeseGmbH/serious-django-permissions/blob/master/serious_django_permissions/management/commands/create_groups.py#L24)
Therefore `create_groups.Command.handle()` creates the `groups` and the `permissions`.
Therefore `create_groups.Command.handle()` is already executing the operations requested for  `setup_permissions()` and `setup_permissions()` has the purpose of making them more accessible?

**Comment by cobalamin** [comment]
Looks just right to me :)

Yeah, you get that right. The reason the `create_permissions` management command is provided at all is that you can use the class-based permissions feature of this package independently of the class-based groups feature. But as soon as you use groups, you define these groups in terms of the permissions they have. That means that you can't create groups without creating permissions first, so that's why `create_groups` calls `create_permissions`. It wouldn't make sense from a usability perspective to error on the console when calling `create_groups` just because no(t all) permissions referenced by some group are present yet.

**Comment by cobalamin** [comment]
You could merge this right away, or adjust the tests accordingly to call the helper methods, and then merge.
